formatters:
  enable:
    - gofmt
    - goimports
  settings: # please keep this alphabetized
    goimports:
      local-prefixes:
        - go.etcd.io # Put imports beginning with prefix after 3rd-party packages.
issues:
  max-same-issues: 0
linters:
  default: none
  enable: # please keep this alphabetized
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - testifylint
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings: # please keep this alphabetized
    staticcheck:
      checks:
        - all
        - -QF1003 # Convert if/else-if chain to tagged switch
        - -QF1004 # Use strings.ReplaceAll instead of strings.Replace with n == -1
        - -QF1010 # Convert slice of bytes to string when printing it
        - -QF1011 # Omit redundant type from variable declaration
        - -ST1003 # Poorly chosen identifier
        - -ST1005 # Incorrectly formatted error string
        - -ST1006 # Poorly chosen receiver name
        - -ST1012 # Poorly chosen name for error variable
        - -ST1016 # Use consistent method receiver names
        - -ST1023 # Redundant type in variable declaration
    testifylint:
      disable:
        - go-require
      enable-all: true
      formatter:
        require-f-funcs: true
version: "2"
