---
name: Reusable Cross-Platform Build Workflow
on:
  workflow_call:
    inputs:
      archs:
        required: true
        type: string
      os:
        required: true
        type: string
permissions: read-all

jobs:
  cross-build:
    strategy:
      matrix:
        arch: ${{ fromJSON(inputs.archs) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - id: goversion
      run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ steps.goversion.outputs.goversion }}
    - name: Build for ${{ inputs.os }}/${{ matrix.arch }}
      run: |
        GOOS=${{ inputs.os }} GOARCH=${{ matrix.arch }} go build ./...
