---
name: Reusable Cross-Platform Build Workflow
on:
  workflow_call:
    inputs:
      archs:
        required: true
        type: string
      os:
        required: true
        type: string
permissions: read-all

jobs:
  cross-build:
    strategy:
      matrix:
        arch: ${{ fromJSON(inputs.archs) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - id: goversion
      run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ steps.goversion.outputs.goversion }}
    - name: Build for ${{ inputs.os }}/${{ matrix.arch }}
      run: |
        GOOS=${{ inputs.os }} GOARCH=${{ matrix.arch }} go build ./...
