name: Robustness Test
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: |
          make gofail-enable
          # build bbolt with failpoint
          go install ./cmd/bbolt
          sudo -E PATH=$PATH make test-robustness
