name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          days-before-stale: 90
          days-before-close: 21
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: 'stage/tracked'
          exempt-pr-labels: 'stage/tracked'
