---
name: Tests WASM
permissions: read-all
on: [push, pull_request]
jobs:
  test-wasm-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'
      - name: Run WASM JS tests
        run: |
          env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            GOCACHE="$GOCACHE" \
            GOPATH="$GOPATH" \
            GOROOT="$(go env GOROOT)" \
            make test-wasm

  test-wasm-wasip1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Install wazero
        run: go install github.com/tetratelabs/wazero/cmd/wazero@latest
      - name: Run WASM wasip1 tests
        run: |
          make test-wasip1
