---
name: Tests ARM64
permissions: read-all
on: [push, pull_request]
jobs:
  test-linux-arm64:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-24.04-arm
  test-linux-arm64-race:
    uses: ./.github/workflows/tests-template.yml
    with:
      runs-on: ubuntu-24.04-arm
      targets: "['linux-unit-test-4-cpu-race']"

  coverage:
    needs:
      - test-linux-arm64
      - test-linux-arm64-race
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: make coverage
